apiVersion: v1
kind: ConfigMap
metadata:
  name: product-cm
  labels:
    app: bigPurple
    service: product
data:
  ASPNETCORE_ENVIRONMENT: Development
  AzureServiceBusEnabled: "False"
  AzureStorageEnabled: "False"
  ConnectionString: Server=sqldata;Database=BigPurpleBank.Product.API.ProductDb;User Id=sa;Password=Pass@word
  EventBusConnection: rabbitmq
  GRPC_PORT: "81"
  OrchestratorType: K8S
  PATH_BASE: /product-api
  PORT: "80"
  UseCustomizationData: "False"
