apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    app: bigPurple
    service: product
spec:
  replicas: 1
  selector:
    matchLabels:
      service: product
  template:
    metadata:
      labels:
        app: bigPurple
        service: product
    spec:
      containers:
        - name: product-api
          image: {{ .Values.registry }}/product.api:linux-net6-product
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 81
              protocol: TCP
          livenessProbe:
            httpGet:
              port: 80
              path: /liveness
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              port: 80
              path: /hc
            initialDelaySeconds: 90
            periodSeconds: 60
            timeoutSeconds: 5
          envFrom:
            - configMapRef:
                name: product-cm
