apiVersion: v1
kind: Service
metadata:
  name: product-api
  labels:
    app: bigPurple
    service: product
spec:
  ports:
    - port: 80
      protocol: TCP
      name: http
    - port: 81
      protocol: TCP
      name: grpc
  selector:
    service: product
