version: '3.4'

services:
  product.api:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: src/API/Product/Product.API/
      dockerfile: Dockerfile
    ports: 
      - "5901:80"
    depends_on:
        - sqldata
  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
        SA_PASSWORD: "Pass@word"
        ACCEPT_EULA: "Y"
