apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: bigPurple
    service: rabbitmq
spec:
  ports:
    - port: 5672
      protocol: TCP
      name: rabbitmq
  selector:
    service: rabbitmq
