apiVersion: apps/v1
kind: Deployment
metadata:
  name: nosqldata
  labels:
    app: bigPurple
    service: nosqldata
spec:
  replicas: 1
  selector:
    matchLabels:
      service: nosqldata
  template:
    metadata:
      labels:
        app: bigPurple
        service: nosqldata
    spec:
      containers:
        - name: nosqldata
          image: mongo
          ports:
            - name: mongodb
              containerPort: 27017
              protocol: TCP
